#!/usr/bin/env bash

set -ex

if git log --pretty=full -1 | grep 'skip ci'; then
  exit 0
fi

echo "ARWEAVE_IMAGE_TAG=$ARWEAVE_IMAGE_TAG" > .env
echo "ENGINE_IMAGE_TAG=$ENGINE_IMAGE_TAG" >> .env
git add .env
if git commit -m "Update service container image tags"; then
  ./bin/feature-tests
  git push
fi
