#!/usr/bin/env bash

set -ex

echo "ARWEAVE_COMMIT=$ARWEAVE_COMMIT" > .env
echo "ARWEAVE_IMAGE_TAG=$ARWEAVE_IMAGE_TAG" >> .env
echo "ENGINE_COMMIT=$ENGINE_COMMIT" >> .env
echo "ENGINE_IMAGE_TAG=$ENGINE_IMAGE_TAG" >> .env
git add .env
if git commit -m "Update container image tags [skip ci]"; then
  mkdir -p /dev/hugepages
  ./bin/feature-tests
  git push
fi

if [ -n "${DOCS_BUCKET}" ]; then
  asciidoctor -D out docs/usage.adoc
  aws s3 sync --delete out "s3://${DOCS_BUCKET}/strongpool-node/${BRANCH}/docs/"
fi

record-success
