#!/usr/bin/env bash

set -ex

# TODO fix lint issue
source .env

NEW_ARWEAVE_COMMIT="$ARWEAVE_COMMIT"
NEW_ENGINE_COMMIT="$ENGINE_COMMIT"

git checkout main

# TODO fix lint issue
source .env

cd engine && git log --oneline "$ENGINE_COMMIT".."$NEW_ENGINE_COMMIT"
