#!/usr/bin/env bash

set -ex

# Copy the latest successfully integrated commit hashes
source $CODEBUILD_SRC_DIR/.env
NEW_ARWEAVE_COMMIT=$ARWEAVE_COMMIT
NEW_ENGINE_COMMIT=$ENGINE_COMMIT

# Load the currently released commit hashes from the main branch
git checkout main
source $CODEBUILD_SRC_DIR/.env

# Switch back to the develop branch
git checkout develop

git clone "https://strongpool-builds:$GITHUB_TOKEN@github.com/Strongpool/arweave.git"
git clone "https://strongpool-builds:$GITHUB_TOKEN@github.com/Strongpool/engine.git"

release_notes=$CODEBUILD_SRC_DIR/release_notes

echo "Strongpool Node Release Notes" > $release_notes

echo >> $release_notes
echo "Strongpool Node changes:" >> $release_notes
git log --oneline "main..$CODEBUILD_RESOLVED_SOURCE_VERSION" >> $release_notes

echo >> $release_notes
echo "Engine changes:" >> $release_notes
cd $CODEBUILD_SRC_DIR/engine && git log --oneline "$ENGINE_COMMIT..$NEW_ENGINE_COMMIT" >> $release_notes

echo >> $release_notes
echo "Arweave changes:" >> $release_notes
cd $CODEBUILD_SRC_DIR/arweave && git log --oneline "$ARWEAVE_COMMIT..$NEW_ARWEAVE_COMMIT" >> $release_notes

release_tag=$(voom-like-version)
gh release create $release_tag --draft --target develop --notes-files $release_notes
