---

version: '3.0'
services:
  arweave:
    image: ghcr.io/strongpool/arweave:latest
    restart: on-failure
    ports:
      - 1984:1984
    volumes:
      - type: bind
        source: ./data
        target: /data
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    command: ${ARWEAVE_ARGS}
