version: "3.9"
services:
  arweave:
    image: "arweave:latest"
    restart: on-failure
    ports:
      - "1984:1984"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - ARWEAVE_ARGS
