---

version: '3.0'
services:
  arweave01:
    image: ${ARWEAVE_IMAGE_REPO}:${ARWEAVE_IMAGE_TAG}
    restart: on-failure
    ports:
      - 1984:1984
    volumes:
      - type: bind
        source: ./data/01
        target: /data
    environment:
      - DEBUG
      - EGRESS_RATE_LIMIT
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    cap_add:
      - NET_ADMIN
    command: ${ARWEAVE_ARGS}
  engine:
    image: ${ENGINE_IMAGE_REPO}:${ENGINE_IMAGE_TAG}
    restart: on-failure
    volumes:
      - type: bind
        source: ./data/01
        target: /data
    environment:
      - INTAKE_URL=http://engine.strongpool.net/intake
      - WSPORAS_PATH=/data/strongpool/arweave/wsporas
      - ENABLE_SIPHON=1
