---

version: '3.0'
services:
  arweave00:
    image: ${ARWEAVE_IMAGE_REPO}:${ARWEAVE_IMAGE_TAG}
    restart: on-failure
    ports:
      - 1984:1984
    volumes:
      - type: bind
        source: ./data/00
        target: /data
    environment:
      - EGRESS_RATE
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    cap_add:
      - NET_ADMIN
    command: ${ARWEAVE_ARGS}
