version: "3.9"
services:
  # TODO add 'restart: unless-stopped' and test it
  arweave:
    image: "arweave:latest"
    ports:
      - "1984:1984"
    volumes:
      - type: bind
        source: ./data
        target: /data
