#!/usr/bin/env bash

set -e

[ -n "$DEBUG" ] && set -x

die () {
    echo >&2 -e "$*"
    exit 1
}

babashka_version="0.4.5"
docker_compose_version="1.29.2"
min_docker_compose_version="1.25.0"

command -v curl > /dev/null || die "Missing required dependency: curl"
command -v docker > /dev/null || die "Missing required dependency: docker\nPlease follow the install instructions here: https://docs.docker.com/engine/install/"

mkdir -p bin data wallets/arweave

# Ensure expected version of docker-compose is available

docker_compose=$(command -v docker-compose || true)
if [ "${docker_compose}" == "" ]; then
    docker_compose="$(pwd)/bin/docker-compose"
fi

installed_docker_compose_version="0.0.0"
if [ -e "${docker_compose}" ]; then
    installed_docker_compose_version=$("${docker_compose}" --version | grep -o '[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}')
fi

if [ "${min_docker_compose_version}" != "$(echo -e "${installed_docker_compose_version}\n${min_docker_compose_version}" | sort -V | head -n1)" ]; then
    echo >&2 "Missing or old version of required dependency: docker-compose; downloading docker-compose version ${docker_compose_version}..."
    curl -sS -L "https://github.com/docker/compose/releases/download/${docker_compose_version}/docker-compose-$(uname -s)-$(uname -m)" -o "${docker_compose}"

    echo "Verify checksum..."
    if ! sha256sum -c bin/.docker-compose.checksum; then
        rm "${docker_compose}"
        exit 1
    fi

    chmod 755 "${docker_compose}"
fi

# Ensure expected version of Babashka is available

bb="$(pwd)/bin/bb"

installed_babashka_version="0.0.0"
if [ -e "${bb}" ]; then
    installed_babashka_version=$("${bb}" --version | grep -o 'v[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}')
fi

if [ "${babashka_version}" != "$(echo -e "${installed_babashka_version}\n${babashka_version}" | sort -V | head -n1)" ]; then
    echo >&2 "Downloading Babashka version ${babashka_version}..."
    bb_tgz="babashka-${babashka_version}-linux-amd64-static.tar.gz"
    curl -sS -L "https://github.com/babashka/babashka/releases/download/v${babashka_version}/${bb_tgz}" -O
    tar -C bin -xzf "${bb_tgz}"
    rm "${bb_tgz}"

    echo "Verify checksum..."
    if ! sha256sum -c bin/.bb.checksum; then
        rm "${bb}"
        exit 1
    fi

    chmod 755 "${bb}"
fi

# TODO check whether huge pages are enabled
# TODO copy example config into correct place on first run

PATH="$(pwd)/bin:$PATH"
export PATH

"${bb}" --classpath src:vendor/docopt.clj/src:vendor/expound/src:vendor/spartan.spec/src --main net.strongpool.node "$@"
