#!/usr/bin/env bash

set -e

die () {
    echo >&2 -e "$*"
    exit 1
}

babashka_version="0.4.5"
docker_version="1.29.2"

command -v curl > /dev/null || die "Missing required dependency: curl"

docker_compose=$(command -v docker-compose)
if [[ "${docker_compose}" == "" ]]; then
    echo >&2 "Missing required dependency: docker-compose; downloading it..."
    docker_compose="$(pwd)/bin/docker-compose"
    curl -L "https://github.com/docker/compose/releases/download/${docker_version}/docker-compose-$(uname -s)-$(uname -m)" -o "${docker_compose}"
    chmod 755 "${docker_compose}"
fi

bb="$(pwd)/bin/bb"

if [[ ! -f "${bb}" ]]; then
    echo >&2 "Downloading Babashka..."
    bb_tgz="babashka-${babashka_version}-linux-amd64-static.tar.gz"
    curl -L "https://github.com/babashka/babashka/releases/download/v${babashka_version}/${bb_tgz}" -O
    tar -C bin -xzf "${bb_tgz}"
    rm "${bb_tgz}"
    chmod 755 "${bb}"
fi

if [[ $# = 0 ]]; then
    $bb --tasks
    exit
fi

PATH="$(pwd)/bin:$PATH"
export PATH

"${bb}" run "$@"
