---

version: 0.2

env:
  shell: bash
  parameter-store:
    GITHUB_TOKEN: '/strongpool/_/_/automation/github-access-token'
    RELEASE_NOTIFICATION_WEBHOOK_URL: '/strongpool/_/_/automation/release-notification-webhook-url'

phases:
  build:
    commands:
      - gh release -R Strongpool/strongpool-node view $RELEASE_TAG -q .body --json body > release_notes
      - curl -X POST -F 'release_notes=<release_notes' $RELEASE_NOTIFICATION_WEBHOOK_URL
