---

version: 0.2

env:
  shell: bash
  parameter-store:
    RELEASE_NOTIFICATION_WEBHOOK_URL: '/strongpool/_/_/automation/release-notification-webhook-url'

phases:
  build:
    commands:
      - curl -sL $RELEASE_NOTES_GIST_URL/raw -O release_notes
      - curl -X POST -F 'release_notes=<release_notes' $RELEASE_NOTIFICATION_WEBHOOK_URL
