---

version: 0.2

env:
  shell: bash
  parameter-store:
    GITHUB_TOKEN: '/strongpool/_/_/automation/github-access-token'
  exported-variables:
    - RELEASE_NOTES_GIST_URL

phases:
  pre_build:
    commands:
      - git config --global user.email "$GIT_USER_EMAIL"
      - git config --global user.name "$GIT_USER_NAME"

  build:
    commands:
      - ./.codebuild/release-notes-build
      - RELEASE_NOTES_GIST_URL=$(cat release_notes_gist_url)

artifacts:
  files:
    - .codebuild/**/*
