---

version: 0.2

env:
  shell: bash
  parameter-store:
    GITHUB_TOKEN: '/strongpool/_/_/build/github-access-token'

phases:
  pre_build:
    commands:
      - git config --global user.email "$GIT_USER_EMAIL"
      - git config --global user.name "$GIT_USER_NAME"

  build:
    commands:
      - ./.codebuild/release-notes-build

artifacts:
  files:
    - .codebuild/**/*
    - release_notes
