---

version: 0.2

env:
  shell: bash
  parameter-store:
    GITHUB_TOKEN: '/strongpool/_/_/automation/github-access-token'

phases:
  pre_build:
    commands:
      - start-docker
      - git config --global user.email "$GIT_USER_EMAIL"
      - git config --global user.name "$GIT_USER_NAME"
      - git remote set-url origin "https://$GITHUB_USER:$GITHUB_TOKEN@github.com/Strongpool/strongpool-node.git"
      - git checkout main
      - git branch --set-upstream-to origin/main

  build:
    commands:
      - ./.codebuild/release-build
