name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Slack start
      uses: voxmedia/github-action-slack-notify-build@v1
      id: slack
      with:
        channel: dev-log
        status: STARTING
        color: warning
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}

    - name: Download clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2021.06.01'

    - name: Install shellcheck
      run: sudo apt-get install shellcheck

    - uses: actions/checkout@v1

    - name: Run clj-kondo
      run: clj-kondo --lint src/clj

    - name: Run shellcheck
      run: shellcheck spnctl

    - name: Notify Slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        # Updates existing message from the first step
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: dev-log
        status: SUCCESS
        color: good

    - name: Notify Slack failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        # Updates existing message from the first step
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: dev-log
        status: FAILED
        color: danger

    - name: Notify Slack failure (build failures channel)
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: build-failures
        status: FAILED
        color: danger
