name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Slack of start
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: dev-log
        status: STARTED
        color: good
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}

    - name: Download clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2021.06.01'

    - name: Install shellcheck
      run: sudo apt-get install shellcheck

    - uses: actions/checkout@v1

    - name: Run clj-kondo
      run: clj-kondo --lint src

    - name: Run shellcheck
      run: shellcheck spnctl
